# SPDX-FileCopyrightText: 2024 KUNBUS GmbH
#
# SPDX-License-Identifier: MIT

---
include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/check-commit/lint-commit.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "reuse-lint.yml"
